config/routes.rb
Rails.application.routes.draw do
  
  resources :marca_maquinaria
  resources :tipo_maquinaria
  resources :registro_mantencions
  resources :maquinaria
  resources :tipo_mantencions
  resources :calificacions
  resources :trabajadors
  resources :tipo_trabajadors
  resources :cultivos
  resources :bodegas
  resources :trabajos
  resources :fitosanitarios
  resources :actividad_paras
  resources :actividads
  resources :representacions
  resources :asesors
  resources :representantes
  resources :campos
  resources :explotacions
  resources :usuarios
  get 'store/index'
  get 'store/show'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/actividad.rb
class Actividad < ApplicationRecord
end

app/models/actividad_para.rb
class ActividadPara < ApplicationRecord
  belongs_to :actividads
end

app/models/asesor.rb
class Asesor < ApplicationRecord
  belongs_to :explotacions
end

app/models/bodega.rb
class Bodega < ApplicationRecord
  belongs_to :actividads
end

app/models/calificacion.rb
class Calificacion < ApplicationRecord
  belongs_to :trabajadors
  belongs_to :tipo_trabajadors
end

app/models/campo.rb
class Campo < ApplicationRecord
  belongs_to :explotacions
end

app/models/cultivo.rb
class Cultivo < ApplicationRecord
  belongs_to :fitosanitarios
  belongs_to :actividads
end

app/models/explotacion.rb
class Explotacion < ApplicationRecord
end

app/models/fitosanitario.rb
class Fitosanitario < ApplicationRecord
  belongs_to :actividads
end

app/models/maquinarium.rb
class Maquinarium < ApplicationRecord
  belongs_to :actividads
end

app/models/representacion.rb
class Representacion < ApplicationRecord
  belongs_to :representantes
  belongs_to :explotacions
end

app/models/representante.rb
class Representante < ApplicationRecord
  belongs_to :explotacions
end

app/models/tipo_mantencion.rb
class TipoMantencion < ApplicationRecord
end

app/models/trabajador.rb
class Trabajador < ApplicationRecord
  belongs_to :tipo_trabajadors
  belongs_to :actividads
end

app/models/trabajo.rb
class Trabajo < ApplicationRecord
  belongs_to :actividads
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/usuario.rb
class Usuario < ApplicationRecord
end

app/controllers/trabajadors_controller.rb
class TrabajadorsController < ApplicationController
  layout "admin"
  
  before_action :set_trabajador, only: %i[ show edit update destroy ]

  # GET /trabajadors or /trabajadors.json
  def index
    @trabajadors = Trabajador.all
  end

  # GET /trabajadors/1 or /trabajadors/1.json
  def show
  end

  # GET /trabajadors/new
  def new
    @trabajador = Trabajador.new
  end

  # GET /trabajadors/1/edit
  def edit
  end

  # POST /trabajadors or /trabajadors.json
  def create
    @trabajador = Trabajador.new(trabajador_params)

    respond_to do |format|
      if @trabajador.save
        format.html { redirect_to @trabajador, notice: "Trabajador was successfully created." }
        format.json { render :show, status: :created, location: @trabajador }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @trabajador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trabajadors/1 or /trabajadors/1.json
  def update
    respond_to do |format|
      if @trabajador.update(trabajador_params)
        format.html { redirect_to @trabajador, notice: "Trabajador was successfully updated." }
        format.json { render :show, status: :ok, location: @trabajador }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @trabajador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trabajadors/1 or /trabajadors/1.json
  def destroy
    @trabajador.destroy
    respond_to do |format|
      format.html { redirect_to trabajadors_url, notice: "Trabajador was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trabajador
      @trabajador = Trabajador.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def trabajador_params
      params.require(:trabajador).permit(:nombre, :tipo_trabajador, :rut, :carnet_aplicador, :calificacion, :asesor, :email, :telefono, :direccion, :localidad, :comuna, :region, :pais, :foto, :comentarios, :tipo_trabajadors_id, :actividads_id)
    end
end

app/helpers/asesors_helper.rb
module AsesorsHelper
end

app/helpers/bodegas_helper.rb
module BodegasHelper
end

app/helpers/campos_helper.rb
module CamposHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/trabajadors_helper.rb
module TrabajadorsHelper
end

app/views/trabajadors/_form.html.erb
<%= form_with(model: trabajador) do |form| %>
  <% if trabajador.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trabajador.errors.count, "error") %> prohibited this trabajador from being saved:</h2>

      <ul>
        <% trabajador.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-6 mt-2">
    <%= form.label :nombre, class: "form-label" %>
    <%= form.text_field :nombre, class: "form-control" %>
  </div>

  <div class="col-6 mt-2">
    <%= form.label :tipo_trabajador, class: "form-label" %>
    <%= form.text_field :tipo_trabajador, class: "form-control" %>
  </div>

  <div class="col-6 mt-2">
    <%= form.label :rut, class: "form-label" %>
    <%= form.text_field :rut, class: "form-control" %>
  </div>

  <div class="col-6 mt-2">
    <%= form.label :carnet_aplicador, class: "form-label" %>
    <%= form.text_field :carnet_aplicador, class: "form-control" %>
  </div>

  <div class="col-6 mt-2">
    <%= form.label :calificacion, class: "form-label" %>
    <%= form.text_field :calificacion, class: "form-control" %>
  </div>

  <div class="col-6 mt-2">
    <%= form.label :asesor, class: "form-label" %>
    <%= form.text_field :asesor, class: "form-control" %>
  </div>

  <div class="col-6 mt-2">
    <%= form.label :email, class: "form-label" %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="col-6 mt-2">
    <%= form.label :telefono, class: "form-label" %>
    <%= form.text_field :telefono, class: "form-control" %>
  </div>

  <div class="col-6 mt-2">
    <%= form.label :direccion, class: "form-label" %>
    <%= form.text_field :direccion, class: "form-control" %>
  </div>

  <div class="col-6 mt-2">
    <%= form.label :localidad, class: "form-label" %>
    <%= form.text_field :localidad, class: "form-control" %>
  </div>

  <div class="col-6 mt-2">
    <%= form.label :comuna, class: "form-label" %>
    <%= form.text_field :comuna, class: "form-control" %>
  </div>

  <div class="col-6 mt-2">
    <%= form.label :region, class: "form-label" %>
    <%= form.text_field :region, class: "form-control" %>
  </div>

  <div class="col-6 mt-2">
    <%= form.label :pais, class: "form-label" %>
    <%= form.text_field :pais, class: "form-control" %>
  </div>

  <div class="col-6 mt-2">
    <%= form.label :foto, class: "form-label" %>
    <%= form.text_field :foto, class: "form-control" %>
  </div>

  <div class="col-6 mt-2">
    <%= form.label :comentarios, class: "form-label" %>
    <%= form.text_area :comentarios, class: "form-control" %>
  </div>

  <div class="col-6 mt-2">
    <%= form.label :tipo_trabajadors_id, class: "form-label" %>
    <%= form.text_field :tipo_trabajadors_id, class: "form-control" %>
  </div>

  <div class="col-6 mt-2">
    <%= form.label :actividads_id, class: "form-label" %>
    <%= form.text_field :actividads_id, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Crear Trabajador", :class => "btn btn-primary text-decoration-none" %>
  </div>
<% end %>

app/views/trabajadors/edit.html.erb
<script src="https://worksystems.cl/jsproject/bootstrap.bundle.min.js"></script>
    <div class="table-responsive">
        <h1>Edita Trabajador</h1>

        <%= render 'form', trabajador: @trabajador %>

        <div class="actions">
            <%= link_to 'Volver', trabajadors_path, :class => "btn btn-primary text-decoration-none" %>
        </div>
    </div>

app/views/trabajadors/index.html.erb
<script src="https://worksystems.cl/jsproject/bootstrap.bundle.min.js"></script>
<div class="card shadow mb-4">
        <div class="card-header py-3">
                            <h3 class="m-0 font-weight-bold text-primary">Trabajadores</h3>
                            <%= link_to 'Nuevo Trabajador', new_trabajador_path, :class => "btn btn-primary text-decoration-none" %>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">

  <thead>
    <tr>
      <th>Nombre</th>
      <th>Tipo trabajador</th>
      <th>Rut</th>
      <th>Carnet aplicador</th>
      <th>Calificacion</th>
      <th>Asesor</th>
      <th>Email</th>
      <th>Telefono</th>
      <th>Direccion</th>
      <th>Localidad</th>
      <th>Comuna</th>
      <th>Region</th>
      <th>Pais</th>
      <th>Foto</th>
      <th>Comentarios</th>
      <th>Tipo trabajadors</th>
      <th>Actividads</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trabajadors.each do |trabajador| %>
      <tr>
        <td><%= trabajador.nombre %></td>
        <td><%= trabajador.tipo_trabajador %></td>
        <td><%= trabajador.rut %></td>
        <td><%= trabajador.carnet_aplicador %></td>
        <td><%= trabajador.calificacion %></td>
        <td><%= trabajador.asesor %></td>
        <td><%= trabajador.email %></td>
        <td><%= trabajador.telefono %></td>
        <td><%= trabajador.direccion %></td>
        <td><%= trabajador.localidad %></td>
        <td><%= trabajador.comuna %></td>
        <td><%= trabajador.region %></td>
        <td><%= trabajador.pais %></td>
        <td><%= trabajador.foto %></td>
        <td><%= trabajador.comentarios %></td>
        <td><%= trabajador.tipo_trabajadors_id %></td>
        <td><%= trabajador.actividads_id %></td>
        <td><%= link_to 'Mostrar', trabajador, :class => "btn btn-primary text-decoration-none" %></td>
        <td><%= link_to 'Editar', edit_trabajador_path(trabajador), :class => "btn btn-primary text-decoration-none" %></td>
        <td><%= link_to 'Eliminar', trabajador, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-primary text-decoration-none" %></td>
      </tr>
    <% end %>
  </tbody>
<br>
                        
                        </table>
                            </div>
                        </div>
      </div>

</div>
                <!-- /.container-fluid -->

app/views/trabajadors/new.html.erb
<script src="https://worksystems.cl/jsproject/bootstrap.bundle.min.js"></script>
    <div class="table-responsive">

        <h1>Nuevo Trabajador</h1>

        <table class="table table-striped table-sm">
            <%= render 'form', trabajador: @trabajador %>
        </table>

        <div class="actions">
            <%= link_to 'Volver', trabajadors_path, :class => "btn btn-primary text-decoration-none" %>
        </div>
    </div>

app/views/trabajadors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @trabajador.nombre %>
</p>

<p>
  <strong>Tipo trabajador:</strong>
  <%= @trabajador.tipo_trabajador %>
</p>

<p>
  <strong>Rut:</strong>
  <%= @trabajador.rut %>
</p>

<p>
  <strong>Carnet aplicador:</strong>
  <%= @trabajador.carnet_aplicador %>
</p>

<p>
  <strong>Calificacion:</strong>
  <%= @trabajador.calificacion %>
</p>

<p>
  <strong>Asesor:</strong>
  <%= @trabajador.asesor %>
</p>

<p>
  <strong>Email:</strong>
  <%= @trabajador.email %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @trabajador.telefono %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @trabajador.direccion %>
</p>

<p>
  <strong>Localidad:</strong>
  <%= @trabajador.localidad %>
</p>

<p>
  <strong>Comuna:</strong>
  <%= @trabajador.comuna %>
</p>

<p>
  <strong>Region:</strong>
  <%= @trabajador.region %>
</p>

<p>
  <strong>Pais:</strong>
  <%= @trabajador.pais %>
</p>

<p>
  <strong>Foto:</strong>
  <%= @trabajador.foto %>
</p>

<p>
  <strong>Comentarios:</strong>
  <%= @trabajador.comentarios %>
</p>

<p>
  <strong>Tipo trabajadors:</strong>
  <%= @trabajador.tipo_trabajadors_id %>
</p>

<p>
  <strong>Actividads:</strong>
  <%= @trabajador.actividads_id %>
</p>

<%= link_to 'Edit', edit_trabajador_path(@trabajador) %> |
<%= link_to 'Back', trabajadors_path %>