config/routes.rb
Rails.application.routes.draw do
  
  resources :marca_maquinaria
  resources :tipo_maquinaria
  resources :registro_mantencions
  resources :maquinaria
  resources :tipo_mantencions
  resources :calificacions
  resources :trabajadors
  resources :tipo_trabajadors
  resources :cultivos
  resources :bodegas
  resources :trabajos
  resources :fitosanitarios
  resources :actividad_paras
  resources :actividads
  resources :representacions
  resources :asesors
  resources :representantes
  resources :campos
  resources :explotacions
  resources :usuarios
  get 'store/index'
  get 'store/show'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/actividad.rb
class Actividad < ApplicationRecord
end

app/models/actividad_para.rb
class ActividadPara < ApplicationRecord
  belongs_to :actividads
end

app/models/asesor.rb
class Asesor < ApplicationRecord
  belongs_to :explotacions
end

app/models/bodega.rb
class Bodega < ApplicationRecord
  belongs_to :actividads
end

app/models/calificacion.rb
class Calificacion < ApplicationRecord
  belongs_to :trabajadors
  belongs_to :tipo_trabajadors
end

app/models/campo.rb
class Campo < ApplicationRecord
  belongs_to :explotacions
end

app/models/cultivo.rb
class Cultivo < ApplicationRecord
  belongs_to :fitosanitarios
  belongs_to :actividads
end

app/models/explotacion.rb
class Explotacion < ApplicationRecord
end

app/models/fitosanitario.rb
class Fitosanitario < ApplicationRecord
  belongs_to :actividads
end

app/models/maquinarium.rb
class Maquinarium < ApplicationRecord
  belongs_to :actividads
end

app/models/representacion.rb
class Representacion < ApplicationRecord
  belongs_to :representantes
  belongs_to :explotacions
end

app/models/representante.rb
class Representante < ApplicationRecord
  belongs_to :explotacions
end

app/models/tipo_mantencion.rb
class TipoMantencion < ApplicationRecord
end

app/models/trabajador.rb
class Trabajador < ApplicationRecord
  belongs_to :tipo_trabajadors
  belongs_to :actividads
end

app/models/trabajo.rb
class Trabajo < ApplicationRecord
  belongs_to :actividads
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/usuario.rb
class Usuario < ApplicationRecord
end

app/controllers/representacions_controller.rb
class RepresentacionsController < ApplicationController
  layout "admin"
  
  before_action :set_representacion, only: %i[ show edit update destroy ]

  # GET /representacions or /representacions.json
  def index
    @representacions = Representacion.all
  end

  # GET /representacions/1 or /representacions/1.json
  def show
  end

  # GET /representacions/new
  def new
    @representacion = Representacion.new
  end

  # GET /representacions/1/edit
  def edit
  end

  # POST /representacions or /representacions.json
  def create
    @representacion = Representacion.new(representacion_params)

    respond_to do |format|
      if @representacion.save
        format.html { redirect_to @representacion, notice: "Representacion was successfully created." }
        format.json { render :show, status: :created, location: @representacion }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @representacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /representacions/1 or /representacions/1.json
  def update
    respond_to do |format|
      if @representacion.update(representacion_params)
        format.html { redirect_to @representacion, notice: "Representacion was successfully updated." }
        format.json { render :show, status: :ok, location: @representacion }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @representacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /representacions/1 or /representacions/1.json
  def destroy
    @representacion.destroy
    respond_to do |format|
      format.html { redirect_to representacions_url, notice: "Representacion was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_representacion
      @representacion = Representacion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def representacion_params
      params.require(:representacion).permit(:nombre, :descripcion, :representantes_id, :explotacions_id)
    end
end

app/helpers/asesors_helper.rb
module AsesorsHelper
end

app/helpers/bodegas_helper.rb
module BodegasHelper
end

app/helpers/campos_helper.rb
module CamposHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/representacions_helper.rb
module RepresentacionsHelper
end

app/views/representacions/_form.html.erb
<%= form_with(model: representacion) do |form| %>
  <% if representacion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(representacion.errors.count, "error") %> prohibited this representacion from being saved:</h2>

      <ul>
        <% representacion.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion %>
  </div>

  <div class="field">
    <%= form.label :representantes_id %>
    <%= form.text_field :representantes_id %>
  </div>

  <div class="field">
    <%= form.label :explotacions_id %>
    <%= form.text_field :explotacions_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/representacions/edit.html.erb
<h1>Editing Representacion</h1>

<%= render 'form', representacion: @representacion %>

<%= link_to 'Show', @representacion %> |
<%= link_to 'Back', representacions_path %>

app/views/representacions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Representacions</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Representantes</th>
      <th>Explotacions</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @representacions.each do |representacion| %>
      <tr>
        <td><%= representacion.nombre %></td>
        <td><%= representacion.descripcion %></td>
        <td><%= representacion.representantes_id %></td>
        <td><%= representacion.explotacions_id %></td>
        <td><%= link_to 'Show', representacion %></td>
        <td><%= link_to 'Edit', edit_representacion_path(representacion) %></td>
        <td><%= link_to 'Destroy', representacion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Representacion', new_representacion_path %>

app/views/representacions/new.html.erb
<h1>New Representacion</h1>

<%= render 'form', representacion: @representacion %>

<%= link_to 'Back', representacions_path %>

app/views/representacions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @representacion.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @representacion.descripcion %>
</p>

<p>
  <strong>Representantes:</strong>
  <%= @representacion.representantes_id %>
</p>

<p>
  <strong>Explotacions:</strong>
  <%= @representacion.explotacions_id %>
</p>

<%= link_to 'Edit', edit_representacion_path(@representacion) %> |
<%= link_to 'Back', representacions_path %>