config/routes.rb
Rails.application.routes.draw do
  
  resources :marca_maquinaria
  resources :tipo_maquinaria
  resources :registro_mantencions
  resources :maquinaria
  resources :tipo_mantencions
  resources :calificacions
  resources :trabajadors
  resources :tipo_trabajadors
  resources :cultivos
  resources :bodegas
  resources :trabajos
  resources :fitosanitarios
  resources :actividad_paras
  resources :actividads
  resources :representacions
  resources :asesors
  resources :representantes
  resources :campos
  resources :explotacions
  resources :usuarios
  get 'store/index'
  get 'store/show'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/actividad.rb
class Actividad < ApplicationRecord
end

app/models/actividad_para.rb
class ActividadPara < ApplicationRecord
  belongs_to :actividads
end

app/models/asesor.rb
class Asesor < ApplicationRecord
  belongs_to :explotacions
end

app/models/bodega.rb
class Bodega < ApplicationRecord
  belongs_to :actividads
end

app/models/calificacion.rb
class Calificacion < ApplicationRecord
  belongs_to :trabajadors
  belongs_to :tipo_trabajadors
end

app/models/campo.rb
class Campo < ApplicationRecord
  belongs_to :explotacions
end

app/models/cultivo.rb
class Cultivo < ApplicationRecord
  belongs_to :fitosanitarios
  belongs_to :actividads
end

app/models/explotacion.rb
class Explotacion < ApplicationRecord
end

app/models/fitosanitario.rb
class Fitosanitario < ApplicationRecord
  belongs_to :actividads
end

app/models/maquinarium.rb
class Maquinarium < ApplicationRecord
  belongs_to :actividads
end

app/models/representacion.rb
class Representacion < ApplicationRecord
  belongs_to :representantes
  belongs_to :explotacions
end

app/models/representante.rb
class Representante < ApplicationRecord
  belongs_to :explotacions
end

app/models/tipo_mantencion.rb
class TipoMantencion < ApplicationRecord
end

app/models/trabajador.rb
class Trabajador < ApplicationRecord
  belongs_to :tipo_trabajadors
  belongs_to :actividads
end

app/models/trabajo.rb
class Trabajo < ApplicationRecord
  belongs_to :actividads
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/usuario.rb
class Usuario < ApplicationRecord
end

app/controllers/trabajos_controller.rb
class TrabajosController < ApplicationController
  layout "admin"
  
  before_action :set_trabajo, only: %i[ show edit update destroy ]

  # GET /trabajos or /trabajos.json
  def index
    @trabajos = Trabajo.all
  end

  # GET /trabajos/1 or /trabajos/1.json
  def show
  end

  # GET /trabajos/new
  def new
    @trabajo = Trabajo.new
  end

  # GET /trabajos/1/edit
  def edit
  end

  # POST /trabajos or /trabajos.json
  def create
    @trabajo = Trabajo.new(trabajo_params)

    respond_to do |format|
      if @trabajo.save
        format.html { redirect_to @trabajo, notice: "Trabajo was successfully created." }
        format.json { render :show, status: :created, location: @trabajo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @trabajo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trabajos/1 or /trabajos/1.json
  def update
    respond_to do |format|
      if @trabajo.update(trabajo_params)
        format.html { redirect_to @trabajo, notice: "Trabajo was successfully updated." }
        format.json { render :show, status: :ok, location: @trabajo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @trabajo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trabajos/1 or /trabajos/1.json
  def destroy
    @trabajo.destroy
    respond_to do |format|
      format.html { redirect_to trabajos_url, notice: "Trabajo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trabajo
      @trabajo = Trabajo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def trabajo_params
      params.require(:trabajo).permit(:nombre, :descripcion, :actividads_id)
    end
end

app/helpers/asesors_helper.rb
module AsesorsHelper
end

app/helpers/bodegas_helper.rb
module BodegasHelper
end

app/helpers/campos_helper.rb
module CamposHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/trabajos_helper.rb
module TrabajosHelper
end

app/views/trabajos/_form.html.erb
<%= form_with(model: trabajo) do |form| %>
  <% if trabajo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trabajo.errors.count, "error") %> prohibited this trabajo from being saved:</h2>

      <ul>
        <% trabajo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_area :descripcion %>
  </div>

  <div class="field">
    <%= form.label :actividads_id %>
    <%= form.text_field :actividads_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trabajos/edit.html.erb
<h1>Editing Trabajo</h1>

<%= render 'form', trabajo: @trabajo %>

<%= link_to 'Show', @trabajo %> |
<%= link_to 'Back', trabajos_path %>

app/views/trabajos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trabajos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Actividads</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trabajos.each do |trabajo| %>
      <tr>
        <td><%= trabajo.nombre %></td>
        <td><%= trabajo.descripcion %></td>
        <td><%= trabajo.actividads_id %></td>
        <td><%= link_to 'Show', trabajo %></td>
        <td><%= link_to 'Edit', edit_trabajo_path(trabajo) %></td>
        <td><%= link_to 'Destroy', trabajo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trabajo', new_trabajo_path %>

app/views/trabajos/new.html.erb
<h1>New Trabajo</h1>

<%= render 'form', trabajo: @trabajo %>

<%= link_to 'Back', trabajos_path %>

app/views/trabajos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @trabajo.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @trabajo.descripcion %>
</p>

<p>
  <strong>Actividads:</strong>
  <%= @trabajo.actividads_id %>
</p>

<%= link_to 'Edit', edit_trabajo_path(@trabajo) %> |
<%= link_to 'Back', trabajos_path %>