config/routes.rb
Rails.application.routes.draw do
  
  resources :marca_maquinaria
  resources :tipo_maquinaria
  resources :registro_mantencions
  resources :maquinaria
  resources :tipo_mantencions
  resources :calificacions
  resources :trabajadors
  resources :tipo_trabajadors
  resources :cultivos
  resources :bodegas
  resources :trabajos
  resources :fitosanitarios
  resources :actividad_paras
  resources :actividads
  resources :representacions
  resources :asesors
  resources :representantes
  resources :campos
  resources :explotacions
  resources :usuarios
  get 'store/index'
  get 'store/show'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/actividad.rb
class Actividad < ApplicationRecord
end

app/models/actividad_para.rb
class ActividadPara < ApplicationRecord
  belongs_to :actividads
end

app/models/asesor.rb
class Asesor < ApplicationRecord
  belongs_to :explotacions
end

app/models/bodega.rb
class Bodega < ApplicationRecord
  belongs_to :actividads
end

app/models/calificacion.rb
class Calificacion < ApplicationRecord
  belongs_to :trabajadors
  belongs_to :tipo_trabajadors
end

app/models/campo.rb
class Campo < ApplicationRecord
  belongs_to :explotacions
end

app/models/cultivo.rb
class Cultivo < ApplicationRecord
  belongs_to :fitosanitarios
  belongs_to :actividads
end

app/models/explotacion.rb
class Explotacion < ApplicationRecord
end

app/models/fitosanitario.rb
class Fitosanitario < ApplicationRecord
  belongs_to :actividads
end

app/models/maquinarium.rb
class Maquinarium < ApplicationRecord
  belongs_to :actividads
end

app/models/registro_mantencion.rb
class RegistroMantencion < ApplicationRecord
  belongs_to :tipo_mantencions
  belongs_to :maquinaria
end

app/models/representacion.rb
class Representacion < ApplicationRecord
  belongs_to :representantes
  belongs_to :explotacions
end

app/models/representante.rb
class Representante < ApplicationRecord
  belongs_to :explotacions
end

app/models/trabajador.rb
class Trabajador < ApplicationRecord
  belongs_to :tipo_trabajadors
  belongs_to :actividads
end

app/models/trabajo.rb
class Trabajo < ApplicationRecord
  belongs_to :actividads
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/usuario.rb
class Usuario < ApplicationRecord
end

app/controllers/registro_mantencions_controller.rb
class RegistroMantencionsController < ApplicationController
  layout "admin"
  
  before_action :set_registro_mantencion, only: %i[ show edit update destroy ]

  # GET /registro_mantencions or /registro_mantencions.json
  def index
    @registro_mantencions = RegistroMantencion.all
  end

  # GET /registro_mantencions/1 or /registro_mantencions/1.json
  def show
  end

  # GET /registro_mantencions/new
  def new
    @registro_mantencion = RegistroMantencion.new
  end

  # GET /registro_mantencions/1/edit
  def edit
  end

  # POST /registro_mantencions or /registro_mantencions.json
  def create
    @registro_mantencion = RegistroMantencion.new(registro_mantencion_params)

    respond_to do |format|
      if @registro_mantencion.save
        format.html { redirect_to @registro_mantencion, notice: "Registro mantencion was successfully created." }
        format.json { render :show, status: :created, location: @registro_mantencion }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @registro_mantencion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registro_mantencions/1 or /registro_mantencions/1.json
  def update
    respond_to do |format|
      if @registro_mantencion.update(registro_mantencion_params)
        format.html { redirect_to @registro_mantencion, notice: "Registro mantencion was successfully updated." }
        format.json { render :show, status: :ok, location: @registro_mantencion }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @registro_mantencion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registro_mantencions/1 or /registro_mantencions/1.json
  def destroy
    @registro_mantencion.destroy
    respond_to do |format|
      format.html { redirect_to registro_mantencions_url, notice: "Registro mantencion was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_registro_mantencion
      @registro_mantencion = RegistroMantencion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def registro_mantencion_params
      params.require(:registro_mantencion).permit(:nombre, :descripcion, :inspeccion_oficial, :fecha, :costo, :factura, :tipo_mantencions_id, :maquinaria_id)
    end
end

app/helpers/asesors_helper.rb
module AsesorsHelper
end

app/helpers/bodegas_helper.rb
module BodegasHelper
end

app/helpers/campos_helper.rb
module CamposHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registro_mantencions_helper.rb
module RegistroMantencionsHelper
end

app/views/registro_mantencions/_form.html.erb
<%= form_with(model: registro_mantencion) do |form| %>
  <% if registro_mantencion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(registro_mantencion.errors.count, "error") %> prohibited this registro_mantencion from being saved:</h2>

      <ul>
        <% registro_mantencion.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion %>
  </div>

  <div class="field">
    <%= form.label :inspeccion_oficial %>
    <%= form.text_field :inspeccion_oficial %>
  </div>

  <div class="field">
    <%= form.label :fecha %>
    <%= form.date_select :fecha %>
  </div>

  <div class="field">
    <%= form.label :costo %>
    <%= form.text_field :costo %>
  </div>

  <div class="field">
    <%= form.label :factura %>
    <%= form.text_field :factura %>
  </div>

  <div class="field">
    <%= form.label :tipo_mantencions_id %>
    <%= form.text_field :tipo_mantencions_id %>
  </div>

  <div class="field">
    <%= form.label :maquinaria_id %>
    <%= form.text_field :maquinaria_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/registro_mantencions/edit.html.erb
<h1>Editing Registro Mantencion</h1>

<%= render 'form', registro_mantencion: @registro_mantencion %>

<%= link_to 'Show', @registro_mantencion %> |
<%= link_to 'Back', registro_mantencions_path %>

app/views/registro_mantencions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Registro Mantencions</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Inspeccion oficial</th>
      <th>Fecha</th>
      <th>Costo</th>
      <th>Factura</th>
      <th>Tipo mantencions</th>
      <th>Maquinaria</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @registro_mantencions.each do |registro_mantencion| %>
      <tr>
        <td><%= registro_mantencion.nombre %></td>
        <td><%= registro_mantencion.descripcion %></td>
        <td><%= registro_mantencion.inspeccion_oficial %></td>
        <td><%= registro_mantencion.fecha %></td>
        <td><%= registro_mantencion.costo %></td>
        <td><%= registro_mantencion.factura %></td>
        <td><%= registro_mantencion.tipo_mantencions_id %></td>
        <td><%= registro_mantencion.maquinaria_id %></td>
        <td><%= link_to 'Show', registro_mantencion %></td>
        <td><%= link_to 'Edit', edit_registro_mantencion_path(registro_mantencion) %></td>
        <td><%= link_to 'Destroy', registro_mantencion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Registro Mantencion', new_registro_mantencion_path %>

app/views/registro_mantencions/new.html.erb
<h1>New Registro Mantencion</h1>

<%= render 'form', registro_mantencion: @registro_mantencion %>

<%= link_to 'Back', registro_mantencions_path %>

app/views/registro_mantencions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @registro_mantencion.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @registro_mantencion.descripcion %>
</p>

<p>
  <strong>Inspeccion oficial:</strong>
  <%= @registro_mantencion.inspeccion_oficial %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @registro_mantencion.fecha %>
</p>

<p>
  <strong>Costo:</strong>
  <%= @registro_mantencion.costo %>
</p>

<p>
  <strong>Factura:</strong>
  <%= @registro_mantencion.factura %>
</p>

<p>
  <strong>Tipo mantencions:</strong>
  <%= @registro_mantencion.tipo_mantencions_id %>
</p>

<p>
  <strong>Maquinaria:</strong>
  <%= @registro_mantencion.maquinaria_id %>
</p>

<%= link_to 'Edit', edit_registro_mantencion_path(@registro_mantencion) %> |
<%= link_to 'Back', registro_mantencions_path %>